### PR TITLE
Hero section

### PR DESCRIPTION
**Pull request by johnalpha74**
Added the nav section and the headline section to the project according to the Figma template #3. Provided details for the sections.

### CODE REVIEW

**Review by m05e5 — COMMENTED** [review]
Hi @johnalpha74 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

The index.html of this project has already been merged into the main branch. Please kindly delete it from the main branch in the git repo and submit it again for review because the .HTML file is part of the main files that we are supposed to review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by johnalpha74** [comment]
Hi @m05e5 

I have deleted the index.html from the main branch. Is that OK. should I send it for code review again. 

Cheers

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @johnalpha74👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



## Required Changes ♻️
This PR doesn't include the index file as changed so I can not highlight the code. I will request the changes here.
- [ ] Please wrap header section in `<header>` tag and make sure the `<main>` tag start after the `<header>.` This will make sure your code follows best practices and is semantic.
- [ ] Please wrap `<div class="welcome">Welcome</div>`  the logo in anchor tag `<a>.` Logos are supposed to be links.
- [ ] Please wrap all social media icons in the hero section in `<ul>` and `<li>` tags, When we have similar elements on the page it's a good practice to wrap them in a list and It will also make sure the code is semantic.
- [ ] Please hero wrap your navbar menu options in a list.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by uche-inyama — APPROVED** [review]
## :recycle:  Changes Required

Hi @johnalpha74 :wave: 

 Good job so far! 

However, there are some issues that you still need to work on, before going to the next project. But, you are almost there!    

Apologies, I chose **approved** in error. 
    
## Highlights

- [X] The changes requested from the last review were all meet. 
    
    ## Required Changes ♻️
- [ ]  I can see that your last commit was not checked, kindly fix this.
- [ ] There is a conflict within the file(s) in this branch. Kindly resolve it.
    
    ## Optional suggestions
    _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
    
    Cheers and Happy coding!👏👏👏
    
    Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
    Please, remember to tag me in your question so I can receive the notification.
    
    **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
    
    ------
    _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
    ```

**Review by johnalpha74 — COMMENTED** [review]
I have checked this commit.

**Review by danmainah — COMMENTED** [review]
Hi @johnalpha74, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has pull request already been merged to the main branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by thecodechaser — COMMENTED** [review]
## STATUS: APPROVED 🟢

## Hi @johnalpha74👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## NOTE: Never merge a branch before approval.

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
